name: MakeDockerfile
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter config --enable-web
      - run: flutter doctor
      - run: flutter pub get
      - run: dart compile exe bin/drcd.dart -v -o docker/drcd
      - run: flutter build web
      - run: mv build/web docker/web
      - run: chmod +x docker/drcd
      - name: Outputfile
        uses: actions/upload-artifact@v2
        with:
          name: drcd_docker_all
          path: docker
        continue-on-error: true